ARG KIBANA_VERSION=6.7.1
FROM docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
ARG ALESTALERT_KIBANA_VERSION=6.7.1
ARG ALESTALERT_PLUGIN_VERSION=1.0.3
RUN ./bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/$ALESTALERT_PLUGIN_VERSION/elastalert-kibana-plugin-$ALESTALERT_PLUGIN_VERSION-$ALESTALERT_KIBANA_VERSION.zip
